/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import src.models.Users;
import src.dao.UsersDAO;

/**
 *
 * @author paulo
 */
public class RegisterForm extends javax.swing.JFrame {
    
    private final UsersDAO userDAO;
    
    private static String password;
    private static String email;
    private static String verifPassword;
    private static String customer;

    /**
     * Creates new form LoginForm
     */
    public RegisterForm(UsersDAO userDAO) {
        initComponents();
        initPersoComponents();
        this.userDAO = userDAO;
    }
    
    private void initPersoComponents()
    {
        errorEmailText.setVisible(false); 
        errorPasswordText.setVisible(false);
        individualRadioButton.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        totalBackground = new javax.swing.JPanel();
        backgroundLogin = new javax.swing.JPanel();
        emailText = new javax.swing.JLabel();
        passwordText = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        signUpButton = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        errorEmailText = new javax.swing.JLabel();
        passwordVerifText = new javax.swing.JLabel();
        passwordVerifField = new javax.swing.JPasswordField();
        errorPasswordText = new javax.swing.JLabel();
        BackToLoginButton = new javax.swing.JButton();
        individualRadioButton = new javax.swing.JRadioButton();
        businessRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LoginFrame");

        totalBackground.setBackground(new java.awt.Color(102, 51, 0));

        backgroundLogin.setBackground(new java.awt.Color(255, 153, 51));
        backgroundLogin.setForeground(new java.awt.Color(255, 51, 51));

        emailText.setText("Email");
        emailText.setName("emailText"); // NOI18N

        passwordText.setText("Password");
        passwordText.setName(""); // NOI18N

        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        signUpButton.setText("Sign up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        errorEmailText.setBackground(new java.awt.Color(255, 0, 51));
        errorEmailText.setForeground(new java.awt.Color(255, 0, 51));
        errorEmailText.setText("The email already exist");

        passwordVerifText.setText("Password");
        passwordVerifText.setName(""); // NOI18N

        passwordVerifField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordVerifFieldActionPerformed(evt);
            }
        });

        errorPasswordText.setBackground(new java.awt.Color(255, 0, 51));
        errorPasswordText.setForeground(new java.awt.Color(255, 0, 51));
        errorPasswordText.setText("Not the same password");

        BackToLoginButton.setText("Back To Login");
        BackToLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToLoginButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundLoginLayout = new javax.swing.GroupLayout(backgroundLogin);
        backgroundLogin.setLayout(backgroundLoginLayout);
        backgroundLoginLayout.setHorizontalGroup(
            backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLoginLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(errorPasswordText)
                    .addComponent(errorEmailText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLoginLayout.createSequentialGroup()
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(backgroundLoginLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLoginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(passwordVerifText)
                            .addComponent(passwordText))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordVerifField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLoginLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(signUpButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(BackToLoginButton)
                .addGap(45, 45, 45))
        );
        backgroundLoginLayout.setVerticalGroup(
            backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(errorEmailText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorPasswordText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordText))
                .addGap(35, 35, 35)
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordVerifField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordVerifText))
                .addGap(18, 18, 18)
                .addGroup(backgroundLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackToLoginButton)
                    .addComponent(signUpButton))
                .addGap(32, 32, 32))
        );

        individualRadioButton.setText("Individual");
        individualRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                individualRadioButtonActionPerformed(evt);
            }
        });

        businessRadioButton.setText("Business");
        businessRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                businessRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout totalBackgroundLayout = new javax.swing.GroupLayout(totalBackground);
        totalBackground.setLayout(totalBackgroundLayout);
        totalBackgroundLayout.setHorizontalGroup(
            totalBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, totalBackgroundLayout.createSequentialGroup()
                .addGap(0, 170, Short.MAX_VALUE)
                .addGroup(totalBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(individualRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(businessRadioButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(backgroundLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        totalBackgroundLayout.setVerticalGroup(
            totalBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(totalBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(individualRadioButton)
                .addGap(74, 74, 74)
                .addComponent(businessRadioButton)
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
      
    }//GEN-LAST:event_emailFieldActionPerformed

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
        password = passwordField.getText();
        verifPassword = passwordVerifField.getText();
        email = emailField.getText();
        
        if(individualRadioButton.isSelected())
        {
            customer = "individual";
        }
        else
        {
            customer = "business";
        }
        
        //System.out.println(loginDAO.getLoginByEmail("paul.gommard@edu.ece.fr").getEmail());
        
        if(!verifPassword.isEmpty() && verifPassword.equals(password))
        {
            errorPasswordText.setVisible(false);
            
            if(userDAO.getUserByEmail(email).getEmail() == null)
            {
                errorEmailText.setVisible(false); 
                
                Users newUser = new Users();
                newUser.setEmail(email);
                newUser.setPassword(password);
                newUser.setCustomer(customer);
                
                userDAO.saveUser(newUser);
                
                setVisible(false);
                new LoginForm(userDAO).setVisible(true);
            }
            else
            {
               errorEmailText.setVisible(true);               
            }
        }
        else
        {
            errorPasswordText.setVisible(true);
        }
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordVerifFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordVerifFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordVerifFieldActionPerformed

    private void BackToLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToLoginButtonActionPerformed
        setVisible(false);
        new LoginForm(userDAO).setVisible(true);
    }//GEN-LAST:event_BackToLoginButtonActionPerformed

    private void individualRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_individualRadioButtonActionPerformed
        if(!individualRadioButton.isSelected())
        {
            individualRadioButton.setSelected(true);
            
            
        }
        else if(individualRadioButton.isSelected())
        {
            businessRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_individualRadioButtonActionPerformed

    private void businessRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_businessRadioButtonActionPerformed
        if(!businessRadioButton.isSelected())
        {
            businessRadioButton.setSelected(true);
            
        }
        else if(businessRadioButton.isSelected())
        {
            individualRadioButton.setSelected(false);
        }
    }//GEN-LAST:event_businessRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToLoginButton;
    private javax.swing.JPanel backgroundLogin;
    private javax.swing.JRadioButton businessRadioButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailText;
    private javax.swing.JLabel errorEmailText;
    private javax.swing.JLabel errorPasswordText;
    private javax.swing.JRadioButton individualRadioButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordText;
    private javax.swing.JPasswordField passwordVerifField;
    private javax.swing.JLabel passwordVerifText;
    private javax.swing.JButton signUpButton;
    private javax.swing.JPanel totalBackground;
    // End of variables declaration//GEN-END:variables
}
